# Generated by Django 4.2.4 on 2023-08-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_total_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
